Ed/display nearest buildings
esmason/roomr pull request #17
Opened 2017-03-06 23:49 UTC by esmason

This PR adds the following functionality:
- remove autopublish and use explicit pub/sub to access DB data from client
- simplify front end by refactoring component state to App.state (i.e. take state out of presentational components)
- added marker component to facilitate the previous point (and also to let react deal with re-render logic)
- other small changes such as stylistic fixes (whitespace etc.)

I would like to add [redux](https://github.com/reactjs/redux) to our app because I think it will make things easier as the front end becomes more complex. I can either do it on this branch on make a new branch and implement it after merging this one. I imagine there will be a moderate amount of changes required to do so. (maybe as many as there are currently in this PR).

2017-03-07 02:03 UTC, JordanRoth requested changes
I don't know enough about React to give better feedback on the actual content, so this is mostly style feedback. Maybe try `reformat code` instead of `auto-indent lines` on IntelliJ.

2017-03-07 02:03 UTC, JordanRoth commented on imports/lib/google-map.js
> +import Marker from '../ui/marker'
Should we put this in curly braces for consistency?

2017-03-07 02:03 UTC, JordanRoth commented on imports/lib/google-map.js
> +                GoogleMaps.maps[this.name].instance,
Weird syntax here. Shouldn't the comma either not exist, or there be a second argument?

2017-03-07 02:03 UTC, JordanRoth commented on imports/lib/google-map.js
> +        if (this.props.userLocation!=null) {
Need space around the comparison operator. If you're checking if something is null in Javascript, you can (and probably should) just write: `if (!var)` as it's cleaner.

2017-03-07 02:03 UTC, JordanRoth commented on imports/lib/google-map.js
> +                            lat:building.latitude,
Missing space after ;

2017-03-07 02:03 UTC, JordanRoth commented on imports/lib/google-map.js
> +    initMarker(position){
Missing space before {.

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
> +
Extra line

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
> +        if (this.state.subscription!=null) {
Same as above

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
> +                        availableBuildings.find({}).fetch()[0].buildings : [],
Spaces around ternary operators

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
> +
Extra line

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
>              return "Lat: ".concat(this.state.userLocation.lat(), " Lng: ",this.state.userLocation.lng());
Better to use the + operator or  for interpolation. This is confirmed by airbnb.

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/App.jsx
> +                       userLocation={this.state.userLocation}
Space around = operator.

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/marker.jsx
> +    componentWillUnmount(){
Space before {

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/marker.jsx
> +    render(){
Space before {

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/my-map.jsx
> +                onReady={this.handleOnReady.bind(this)}
3x space around = operator.

2017-03-07 02:03 UTC, JordanRoth commented on imports/ui/my-map.jsx
>              //  getDirections(map, "Life sciences centre, UBC, Vancouver", "ICICS, UBC, Vancouver");
Remove commented out code.

2017-03-07 02:03 UTC, JordanRoth commented on server/main.js
> +            console.log("got buildings");
Remove console.log

2017-03-07 03:44 UTC, JordanRoth commented on imports/lib/google-map.js
> +                GoogleMaps.maps[this.name].instance,
This is airbnb compliant. Disregard.

2017-03-07 04:57 UTC, esmason commented on imports/lib/google-map.js
> +import Marker from '../ui/marker'
if you want to do this have to wrap export with `{[export]}`.

seems like this is not typically done for components https://github.com/meteor/simple-todos-react/blob/master/imports/ui/App.jsx#L8

2017-03-11 05:37 UTC, JordanRoth approved these changes

2017-03-11 07:24 UTC, merged