Get closest free buildings
esmason/roomr pull request #5
Opened 2017-02-24 06:52 UTC by JordanRoth

This PR also includes all of the changes from this (now-defunct) [PR](https://github.com/esmason/roomr/pull/2). Please see that PR for notes on many changes.

In addition, the ability to call a single function to get the n closest buildings (where each building has at least one free room) to some given point at some given time on some given day has been added. No front-end work was done.

2017-02-25 02:24 UTC, IMCampbell requested changes

2017-02-25 02:24 UTC, IMCampbell commented on server/database_access/retrieve-buildings.js
> +            let clashingRoomSlot = false;
Rename clash to something that implies the room is occupied, not clashing with another roomslot.

2017-02-25 02:24 UTC, IMCampbell commented on server/database_access/retrieve-buildings.js
> +function getReturnBuildingObject(building, availableRooms) {
Maybe rename to getFrontEndBuildingObject or getDisplayBuildingObject?

2017-02-25 02:24 UTC, IMCampbell commented on server/main.js
> +import '../imports/api/times.js'
;

2017-02-25 02:24 UTC, IMCampbell commented on server/main.js
> +import './database_access/retrieve-buildings.js'
;

2017-02-25 02:24 UTC, IMCampbell commented on server/utilities/distance-utils.js
> +export function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
Comment code, and credit http://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula

2017-02-26 00:28 UTC, esmason commented on server/main.js
> +import '../imports/database/collections';
add helper function to collections.js instead of using import to run file

2017-02-26 01:53 UTC, esmason commented
recommended database changes

- Separate each collection into it's own file
- Move all insert and update functionality to custom helper functions
- schema can be validated in helper functions

2017-02-26 01:54 UTC, esmason reviewed
recommended database changes

  -  Separate each collection into it's own file
 -   Move all insert and update functionality to custom helper functions
 -  schema can be validated in helper functions

2017-02-26 01:54 UTC, esmason commented on server/main.js
> +import './database_access/retrieve-buildings.js'
try removing first 3 lines of file

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/database-construction.js
> +   {
{ -> }

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/database-construction.js
> +    const newBuildings = [];
call array "Buildings"

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/database-construction.js
> +function parseBuilding(roomSlot, newBuildings) {
--> `function getOrCreateBuilding(roomSlot, Buildings)`

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/database-construction.js
> +function parseRoom(roomSlot, building) {
rename `function getOrCreateRoom(roomSlot, building)`

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/database-construction.js
> +function parseRoomSlot(roomSlot, building, room) {
rename `createRoomSlot`

2017-02-26 01:54 UTC, esmason commented on server/utilities/date-time-utils.js
> +        return LocalTime.parse((`0${ split[0] }:${ split[1] }`))
change `('0${ split[0] }:${ split[1] }')` to `'0'.concat(time)`

2017-02-26 01:54 UTC, esmason commented on server/database_initialization/geocoder.js
> +function updateBuildingWithLatLon(newLat, newLon, id) {
validate lat lon (potential add helper fn to Building)

2017-02-26 04:32 UTC, IMCampbell commented on server/database_initialization/database-construction.js
>          let newBuilding = {
should be buildings?

2017-02-26 04:36 UTC, IMCampbell requested changes

2017-02-26 04:36 UTC, IMCampbell commented on server/database_initialization/database-construction.js
>      let building = Buildings.findOne({name: roomSlot['building']});
This could be refactored to be clearer, too many building-like variables.

2017-02-26 04:37 UTC, IMCampbell approved these changes
Neato!

2017-02-26 04:38 UTC, merged